"""initial_schema_postgres

Revision ID: 55686459f30b
Revises: 
Create Date: 2026-05-20 00:29:19.027277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55686459f30b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reagents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_cn', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('cas_no', sa.String(length=100), nullable=True),
    sa.Column('standard_name', sa.String(length=200), nullable=True),
    sa.Column('purity_grade', sa.String(length=100), nullable=True),
    sa.Column('alias_name', sa.String(length=300), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_preset', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('specification', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('current_quantity', sa.Float(), nullable=False),
    sa.Column('warning_threshold', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('hazard_level', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('msds_url', sa.String(length=500), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reagents_cas_no'), 'reagents', ['cas_no'], unique=False)
    op.create_index(op.f('ix_reagents_category'), 'reagents', ['category'], unique=False)
    op.create_index(op.f('ix_reagents_expiry_date'), 'reagents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_reagents_hazard_level'), 'reagents', ['hazard_level'], unique=False)
    op.create_index(op.f('ix_reagents_id'), 'reagents', ['id'], unique=False)
    op.create_index(op.f('ix_reagents_location'), 'reagents', ['location'], unique=False)
    op.create_index(op.f('ix_reagents_name_cn'), 'reagents', ['name_cn'], unique=False)
    op.create_index(op.f('ix_reagents_name_en'), 'reagents', ['name_en'], unique=False)
    op.create_index(op.f('ix_reagents_standard_name'), 'reagents', ['standard_name'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_created_at'), 'sync_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_logs_id'), 'sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sync_logs_source'), 'sync_logs', ['source'], unique=False)
    op.create_index(op.f('ix_sync_logs_status'), 'sync_logs', ['status'], unique=False)
    op.create_index(op.f('ix_sync_logs_sync_type'), 'sync_logs', ['sync_type'], unique=False)
    op.create_table('tencent_docs_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('open_id', sa.String(length=128), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tencent_docs_tokens_expires_at'), 'tencent_docs_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_tencent_docs_tokens_id'), 'tencent_docs_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_tencent_docs_tokens_open_id'), 'tencent_docs_tokens', ['open_id'], unique=False)
    op.create_index(op.f('ix_tencent_docs_tokens_provider'), 'tencent_docs_tokens', ['provider'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('wechat_openid', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_wechat_openid'), 'users', ['wechat_openid'], unique=True)
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reagent_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reagent_id'], ['reagents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_alert_type'), 'alert_events', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_events_created_at'), 'alert_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_events_id'), 'alert_events', ['id'], unique=False)
    op.create_index(op.f('ix_alert_events_is_resolved'), 'alert_events', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_alert_events_level'), 'alert_events', ['level'], unique=False)
    op.create_index(op.f('ix_alert_events_reagent_id'), 'alert_events', ['reagent_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('inventory_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reagent_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('quantity_change', sa.Float(), nullable=False),
    sa.Column('before_quantity', sa.Float(), nullable=False),
    sa.Column('after_quantity', sa.Float(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('operator_name', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_sheet', sa.String(length=100), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('source_col', sa.Integer(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reagent_id'], ['reagents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_records_created_at'), 'inventory_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_records_event_date'), 'inventory_records', ['event_date'], unique=False)
    op.create_index(op.f('ix_inventory_records_id'), 'inventory_records', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_records_operation_type'), 'inventory_records', ['operation_type'], unique=False)
    op.create_index(op.f('ix_inventory_records_operator_id'), 'inventory_records', ['operator_id'], unique=False)
    op.create_index(op.f('ix_inventory_records_reagent_id'), 'inventory_records', ['reagent_id'], unique=False)
    op.create_index(op.f('ix_inventory_records_source'), 'inventory_records', ['source'], unique=False)
    op.create_index(op.f('ix_inventory_records_source_hash'), 'inventory_records', ['source_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_records_source_hash'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_source'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_reagent_id'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_operator_id'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_operation_type'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_id'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_event_date'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_created_at'), table_name='inventory_records')
    op.drop_table('inventory_records')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alert_events_reagent_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_level'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_is_resolved'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_created_at'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alert_type'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_users_wechat_openid'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tencent_docs_tokens_provider'), table_name='tencent_docs_tokens')
    op.drop_index(op.f('ix_tencent_docs_tokens_open_id'), table_name='tencent_docs_tokens')
    op.drop_index(op.f('ix_tencent_docs_tokens_id'), table_name='tencent_docs_tokens')
    op.drop_index(op.f('ix_tencent_docs_tokens_expires_at'), table_name='tencent_docs_tokens')
    op.drop_table('tencent_docs_tokens')
    op.drop_index(op.f('ix_sync_logs_sync_type'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_status'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_source'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_id'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_created_at'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_reagents_standard_name'), table_name='reagents')
    op.drop_index(op.f('ix_reagents_name_en'), table_name='reagents')
    op.drop_index(op.f('ix_reagents_name_cn'), table_name='reagents')
    op.drop_index(op.f('ix_reagents_location'), table_name='reagents')
    op.drop_index(op.f('ix_reagents_id'), table_name='reagents')
    op.drop_index(op.f('ix_reagents_hazard_level'), table_name='reagents')
    op.drop_index(op.f('ix_reagents_expiry_date'), table_name='reagents')
    op.drop_index(op.f('ix_reagents_category'), table_name='reagents')
    op.drop_index(op.f('ix_reagents_cas_no'), table_name='reagents')
    op.drop_table('reagents')
    # ### end Alembic commands ###
